"""
Django settings for core project.

Generated by 'django-admin startproject' using Django 5.2.

For more information on this file, see
https://docs.djangoproject.com/en/5.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/5.2/ref/settings/
"""
import os
from pathlib import Path
from datetime import timedelta

# Build paths inside the project like this: BASE_DIR / 'subdir'.
BASE_DIR = Path(__file__).resolve().parent.parent

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/5.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure--^)gv9595(=#-ij6vqt72umol17m39gaf%g6x=rr%vjpy6s8b='

# SECURITY WARNING: don't run with debug turned on in production!
DEBUG = True

ALLOWED_HOSTS = [
    "127.0.0.1",
    "localhost",
    "165.22.75.64",
    "api.coderswar.uz"
]

INSTALLED_APPS = [
"jazzmin",
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'corsheaders',
    'rest_framework',
    'drf_yasg',
    'rest_framework_simplejwt',
    'django_filters',
    'apps.userapp',
    'apps.content',
    'apps.mainquest',
    'apps.comment',
    'apps.sidequest',
    'apps.contact',
    'apps.duels',
    'apps.initialtest',

]

MIDDLEWARE = [
    "corsheaders.middleware.CorsMiddleware",
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',

]

ROOT_URLCONF = 'core.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': [],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
            ],
        },
    },
]

REST_FRAMEWORK = {
    'DEFAULT_SCHEMA_CLASS': 'drf_spectacular.openapi.AutoSchema',
    'DEFAULT_AUTHENTICATION_CLASSES': [
        'rest_framework_simplejwt.authentication.JWTAuthentication',
    ],
    'DEFAULT_FILTER_BACKENDS': ['django_filters.rest_framework.DjangoFilterBackend'],
    'DEFAULT_PERMISSION_CLASSES': [
        'rest_framework.permissions.AllowAny',
    ]
}

SIMPLE_JWT = {
    'ACCESS_TOKEN_LIFETIME': timedelta(days=3650),
    'REFRESH_TOKEN_LIFETIME': timedelta(days=36500),
    'ROTATE_REFRESH_TOKENS': False,
    'BLACKLIST_AFTER_ROTATION': False,
    'ALGORITHM': 'HS256',
    'SIGNING_KEY': SECRET_KEY,
    'AUTH_HEADER_TYPES': ('Bearer',),
    'AUTH_TOKEN_CLASSES': ('rest_framework_simplejwt.tokens.AccessToken',),
}

WSGI_APPLICATION = 'core.wsgi.application'

AUTH_USER_MODEL = 'userapp.User'

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': BASE_DIR / 'db.sqlite3',
    }
}

# Password validation
# https://docs.djangoproject.com/en/5.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]

# Internationalization
# https://docs.djangoproject.com/en/5.2/topics/i18n/

LANGUAGE_CODE = 'en-us'

TIME_ZONE = 'UTC'

USE_I18N = True

USE_TZ = True

# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/5.2/howto/static-files/

MEDIA_ROOT = os.path.join(BASE_DIR, "media")

MEDIA_URL = '/media/'
STATIC_URL = '/static/'

MEDIA_URL = '/media/'

# STATICFILES_DIRS = [
#     BASE_DIR / "static",
# ]
JD_CLIENT_ID = '2d6867c57b226adf3644b0c4b879e4e3'
JD_CLIENT_SECRET = '41090e328eaf6cc453b1c3e988c80c2f32dd3f93c6a5f183e72ff03f86270a5d'
JUDGE0_API_KEY = "0aec8801d1msh9e6a1e1a901347ap1ad911jsn249c31bc123e"
JUDGE0_API_HOST = "judge0-ce.p.rapidapi.com"

STATIC_ROOT = os.path.join(BASE_DIR, "static/")

# Default primary key field type
# https://docs.djangoproject.com/en/5.2/ref/settings/#default-auto-field

DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'
EMAIL_BACKEND = 'django.core.mail.backends.smtp.EmailBackend'
EMAIL_HOST = 'smtp.gmail.com'
EMAIL_PORT = 587
EMAIL_USE_TLS = True
EMAIL_HOST_USER = 'xamrayevnurbek00@gmail.com'
EMAIL_HOST_PASSWORD = 'bqua grgr amnh oicy'
CORS_ALLOWED_ORIGINS = [
    "https://165.22.75.64",
    "http://127.0.0.1:8000",
    "https://api.coderswar.uz",
]
CSRF_TRUSTED_ORIGINS = [
    "http://localhost:5173",
    "https://coderswar.uz",
    "https://api.coderswar.uz",
    "https://165.22.75.64",
]

CORS_ALLOW_METHODS = [
    "GET",
    "POST",
    "PUT",
    "PATCH",
    "DELETE",
    "OPTIONS"
]
CORS_ALLOW_HEADERS = [
    "Authorization",
    "Content-Type",
    "Accept",
    "X-CSRFToken"
]
CORS_ALLOW_CREDENTIALS = True
CORS_ALLOW_ALL_ORIGINS = True
JAZZMIN_SETTINGS = {
    "site_title": "Coders War Admin",
    "site_header": "Coders War Boshqaruv Paneli",
    "site_brand": "Coders War",
    "welcome_sign": "Coders War tizimiga xush kelibsiz!",
    "copyright": "© 2025 Coders War",

    "site_logo": "images/logo.png",
    "site_icon": "images/favicon.ico",

    "search_model": [
    "auth.User",
    "userapp.CustomUser",
    "mainquest.Topic",  
],

    "topmenu_links": [
        {"name": "Bosh sahifa", "url": "/", "permissions": ["auth.view_user"]},
        {"model": "auth.User"},
        {"model": "userapp.CustomUser"},
    ],

    "order_with_respect_to": [
        "userapp",
        "content",
        "mainquest",
        "sidequest",
        "duels",
        "comment",
        "contact",
        "initialtest",
    ],

    "show_sidebar": True,
    "language_chooser": True,

    "default_icon_parents": "fas fa-chevron-circle-right",
    "icons": {
        "auth": "fas fa-users-cog",
        "auth.user": "fas fa-user",
        "auth.Group": "fas fa-users",
        "userapp.CustomUser": "fas fa-user-circle",
        "content.Content": "fas fa-book",
        "mainquest.Topic": "fas fa-chalkboard-teacher",
        "sidequest.Assignment": "fas fa-dumbbell",
        "duels.Duel": "fas fa-crosshairs",
        "comment.Comment": "fas fa-comments",
        "contact.ContactMessage": "fas fa-envelope-open-text",
        "initialtest.InitialTest": "fas fa-question-circle",
    },
}



USE_I18N = True
USE_L10N = True
LANGUAGE_CODE = 'uz'
